export const tonicNotes = [
  'C3',
  'C#3',
  'D3',
  'D#3',
  'E3',
  'F3',
  'F#3',
  'G3',
  'G#3',
  'A3',
  'A#3',
  'B3',
];

export const otherNotes = [
  'C3',
  'C#3',
  'D3',
  'D#3',
  'E3',
  'F3',
  'F#3',
  'G3',
  'G#3',
  'A3',
  'A#3',
  'B3',
  'C4',
  'C#4',
  'D4',
  'D#4',
  'E4',
  'F4',
  'F#4',
  'G4',
  'G#4',
  'A4',
  'A#4',
  'B4',
  'C5',
  'C#5',
  'D5',
  'D#5',
  'E5',
  'F5',
  'F#5',
  'G5',
  'G#5',
  'A5',
  'A#5',
  'B5',
];

export const notesPath = {
  C3: { name: 'C', path: 'C3.mp3' },
  'C#3': { name: 'C#', path: 'Cs3.mp3' },
  D3: { name: 'D', path: 'D3.mp3' },
  'D#3': { name: 'D#', path: 'Ds3.mp3' },
  E3: { name: 'E', path: 'E3.mp3' },
  F3: { name: 'F', path: 'F3.mp3' },
  'F#3': { name: 'F#', path: 'Fs3.mp3' },
  G3: { name: 'G', path: 'G3.mp3' },
  'G#3': { name: 'G#', path: 'Gs3.mp3' },
  A3: { name: 'A', path: 'A3.mp3' },
  'A#3': { name: 'A#', path: 'As3.mp3' },
  B3: { name: 'B', path: 'B3.mp3' },
  C4: { name: 'C', path: 'C4.mp3' },
  'C#4': { name: 'C#', path: 'Cs4.mp3' },
  D4: { name: 'D', path: 'D4.mp3' },
  'D#4': { name: 'D#', path: 'Ds4.mp3' },
  E4: { name: 'E', path: 'E4.mp3' },
  F4: { name: 'F', path: 'F4.mp3' },
  'F#4': { name: 'F#', path: 'Fs4.mp3' },
  G4: { name: 'G', path: 'G4.mp3' },
  'G#4': { name: 'G#', path: 'Gs4.mp3' },
  A4: { name: 'A', path: 'A4.mp3' },
  'A#4': { name: 'A#', path: 'As4.mp3' },
  B4: { name: 'B', path: 'B4.mp3' },
  C5: { name: 'C', path: 'C5.mp3' },
  'C#5': { name: 'C#', path: 'Cs5.mp3' },
  D5: { name: 'D', path: 'D5.mp3' },
};
