export const tonicNotes = [
  'C4',
  'C#4',
  'D4',
  'D#4',
  'E4',
  'F4',
  'F#4',
  'G4',
  'G#4',
  'A4',
  'A#4',
  'B4',
];

export const otherNotes = [
  'C4',
  'C#4',
  'D4',
  'D#4',
  'E4',
  'F4',
  'F#4',
  'G4',
  'G#4',
  'A4',
  'A#4',
  'B4',
  'C5',
  'C#5',
  'D5',
  'D#5',
  'E5',
  'F5',
  'F#5',
  'G5',
  'G#5',
  'A5',
  'A#5',
  'B5',
  'C6',
  'C#6',
  'D6',
  'D#6',
  'E6',
  'F6',
  'F#6',
  'G6',
  'G#6',
  'A6',
  'A#6',
  'B6',
];

export const notesPath = {
  C4: { name: 'C', path: 'C4.mp3' },
  'C#4': { name: 'C#', path: 'Cs4.mp3' },
  D4: { name: 'D', path: 'D4.mp3' },
  'D#4': { name: 'D#', path: 'Ds4.mp3' },
  E4: { name: 'E', path: 'E4.mp3' },
  F4: { name: 'F', path: 'F4.mp3' },
  'F#4': { name: 'F#', path: 'Fs4.mp3' },
  G4: { name: 'G', path: 'G4.mp3' },
  'G#4': { name: 'G#', path: 'Gs4.mp3' },
  A4: { name: 'A', path: 'A4.mp3' },
  'A#4': { name: 'A#', path: 'As4.mp3' },
  B4: { name: 'B', path: 'B4.mp3' },
  C5: { name: 'C', path: 'C5.mp3' },
  'C#5': { name: 'C#', path: 'Cs5.mp3' },
  D5: { name: 'D', path: 'D5.mp3' },
  'D#5': { name: 'D#', path: 'Ds5.mp3' },
  E5: { name: 'E', path: 'E5.mp3' },
  F5: { name: 'F', path: 'F5.mp3' },
  'F#5': { name: 'F#', path: 'Fs5.mp3' },
  G5: { name: 'G', path: 'G5.mp3' },
  'G#5': { name: 'G#', path: 'Gs5.mp3' },
  A5: { name: 'A', path: 'A5.mp3' },
  'A#5': { name: 'A#', path: 'As5.mp3' },
  B5: { name: 'B', path: 'B5.mp3' },
  C6: { name: 'C', path: 'C6.mp3' },
  'C#6': { name: 'C#', path: 'Cs6.mp3' },
  D6: { name: 'D', path: 'D6.mp3' },
  'D#6': { name: 'D#', path: 'Ds6.mp3' },
  E6: { name: 'E', path: 'E6.mp3' },
  F6: { name: 'F', path: 'F6.mp3' },
  'F#6': { name: 'F#', path: 'Fs6.mp3' },
  G6: { name: 'G', path: 'G6.mp3' },
  'G#6': { name: 'G#', path: 'Gs6.mp3' },
  A6: { name: 'A', path: 'A6.mp3' },
  'A#6': { name: 'A#', path: 'As6.mp3' },
  B6: { name: 'B', path: 'B6.mp3' },
};
